version: '3.9'
services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: shop
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
    ports:
      - "5532:5432"

  auth:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=pass123
    #     - KC_PROXY=edge
    ports:
      - '8180:8080'
    restart: always
    command:
      - start-dev
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
volumes:
  keycloak_data: